env:
  PORT: 5600
  ROOT_URL: http://127.0.0.1:5600
datasources:
  default:
    connection: 
      url: mongodb://127.0.0.1/steedos
  mattermost:
    connection: 
      driver: postgres
      url: postgresql://mmuser:mmuser_password@192.168.0.21:5432/mattermost
    objectFiles: 
      - "./src"
    appFiles:
      - "./src/mattermost.app.yml"
public:
  cfs:
    store: "local"
    local: 
      folder: "./storage"