env:
  PORT: 5600
datasources:
  default:
    connection: 
      host: 127.0.0.1
      database: steedos
  mongo:
    connection: 
      driver: postgres
      url: postgresql://mmuser:mmuser_password@192.168.0.21:5432/mattermost
    objects: 
      - "./src"
    apps:
      - "./src/mattermost.app.yml"
cfs:
  store: "local"
  local: 
    folder: "./storage"